import { Product } from './store';

const Q  = '?auto=format&fit=crop&w=800&q=85';

// ── Electric Scooter images — custom Cloudinary (AI-generated, no branding) ──
const SCOOTER = {
  s1: 'https://res.cloudinary.com/dtg3lepr4/image/upload/v1779860383/Gemini_Generated_Image_il0uf9il0uf9il0u_olcktj.png',
  s2: 'https://res.cloudinary.com/dtg3lepr4/image/upload/v1779860597/Gemini_Generated_Image_s7d9r7s7d9r7s7d9_df2ypr.png',
  s3: 'https://res.cloudinary.com/dtg3lepr4/image/upload/v1779860916/Gemini_Generated_Image_5anxkd5anxkd5anx_qns1xi.png',
  s4: 'https://res.cloudinary.com/dtg3lepr4/image/upload/v1779861098/Gemini_Generated_Image_gnqtmygnqtmygnqt_trj4au.png',
};

export const products: Product[] = [
  {
    id: 'raftaar-sl',
    name: 'RAFTAAR SL',
    slug: 'raftaar-sl',
    price: 74999,
    originalPrice: 89999,
    images: [
      SCOOTER.s1,   // white scooter, urban street
      SCOOTER.s2,   // yellow modern scooter
    ],
    category: 'Electric Scooters',
    badge: 'Best Seller',
    specs: {
      range: '120 km',
      topSpeed: '65 km/h',
      motor: '1000W BLDC',
      battery: '60V 30Ah Lithium',
      chargingTime: '4-5 Hours',
      weight: '98 kg',
    },
    colors: ['#1a1a2e', '#0a3d62', '#c0392b', '#2ecc71'],
    description: 'City-focused performance with a high-tensile frame, regenerative braking, and smart connected controls.',
    features: ['LED Headlamp', 'Digital Dashboard', 'Mobile App Connected', 'Anti-theft Alarm', 'Regenerative Braking', 'USB Charging'],
    inStock: true,
  },
  {
    id: 'raftaar-dl',
    name: 'RAFTAAR DL',
    slug: 'raftaar-dl',
    price: 84999,
    originalPrice: 99999,
    images: [
      SCOOTER.s3,   // modern scooter + helmet, stone wall
      SCOOTER.s4,   // white scooter red seat, garden
    ],
    category: 'Electric Scooters',
    badge: 'New Launch',
    specs: {
      range: '140 km',
      topSpeed: '70 km/h',
      motor: '1200W BLDC Hub',
      battery: '72V 32Ah Lithium',
      chargingTime: '4 Hours',
      weight: '104 kg',
    },
    colors: ['#1a1a2e', '#7f8c8d', '#c0392b'],
    description: 'Extended range and torque-tuned ride quality for riders who want a premium daily commuter.',
    features: ['Dual Battery', 'Fast Charge Support', 'GPS Tracking', 'Keyless Entry', 'Hill Hold Assist', 'LED Tail Lamp'],
    inStock: true,
  },
  {
    id: 'active-s',
    name: 'ACTIVE S',
    slug: 'active-s',
    price: 54999,
    originalPrice: 64999,
    images: [
      SCOOTER.s3,
      SCOOTER.s4,
    ],
    category: 'Electric Scooters',
    badge: 'Popular',
    specs: {
      range: '100 km',
      topSpeed: '55 km/h',
      motor: '800W BLDC',
      battery: '60V 24Ah Lithium',
      chargingTime: '5-6 Hours',
      weight: '88 kg',
    },
    colors: ['#e74c3c', '#3498db', '#2c3e50', '#f39c12'],
    description: 'Compact, stylish, and efficient — the ideal urban scooter with smart ride modes and agile handling.',
    features: ['Tubeless Tyres', 'Hydraulic Brakes', 'Spacious Underseat Storage', 'LED DRL', 'Smart Key', 'Eco/Sport Mode'],
    inStock: true,
  },
  {
    id: 'vega-active-cs3',
    name: 'VEGA ACTIVE CS3',
    slug: 'vega-active-cs3',
    price: 94999,
    originalPrice: 109999,
    images: [
      SCOOTER.s4,
      SCOOTER.s1,
    ],
    category: 'Electric Scooters',
    badge: 'Flagship',
    specs: {
      range: '160 km',
      topSpeed: '80 km/h',
      motor: '1500W PMSM',
      battery: '72V 40Ah Lithium NMC',
      chargingTime: '3.5 Hours',
      weight: '112 kg',
    },
    colors: ['#1a1a2e', '#d4af37', '#c0392b'],
    description: 'A flagship scooter with advanced connectivity, AI ride modes, and premium finish for the most demanding riders.',
    features: ['7" Touchscreen', 'AI Ride Modes', 'Face Unlock', 'OTA Updates', 'Cruise Control', 'Reverse Mode', 'Traction Control'],
    inStock: true,
  },
  {
    id: 'regal-x1',
    name: 'REGAL X1',
    slug: 'regal-x1',
    price: 114999,
    originalPrice: 129999,
    images: [
      `https://images.unsplash.com/photo-1558981403-c5f9899a28bc${Q}`,
      `https://images.unsplash.com/photo-1607088797610-020db7a14cd5${Q}`,
    ],
    category: 'Electric Bikes',
    badge: 'Trail Ready',
    specs: {
      range: '180 km',
      topSpeed: '105 km/h',
      motor: '2500W PMSM',
      battery: '72V 45Ah Lithium',
      chargingTime: '4 Hours',
      weight: '85 kg',
    },
    colors: ['#34495e', '#27ae60', '#e67e22'],
    description: 'A sporty electric bike built for weekend adventure and agile city cruising with premium off-road capability.',
    features: ['Removable Battery', 'Dual Suspension', 'LED Matrix Headlamp', 'Bluetooth App', 'Disc Brakes', 'Rider Modes'],
    inStock: true,
  },
  {
    id: 'regal-x2',
    name: 'REGAL X2',
    slug: 'regal-x2',
    price: 129999,
    originalPrice: 149999,
    images: [
      `https://images.unsplash.com/photo-1623079399942-368de709ea32${Q}`,
      `https://images.unsplash.com/photo-1558980664-10e7170b5df9${Q}`,
    ],
    category: 'Electric Bikes',
    badge: 'Pro Series',
    specs: {
      range: '210 km',
      topSpeed: '120 km/h',
      motor: '3000W PMSM',
      battery: '72V 55Ah Lithium',
      chargingTime: '3.8 Hours',
      weight: '92 kg',
    },
    colors: ['#2c3e50', '#8e44ad', '#ecf0f1'],
    description: 'Track-inspired performance electric bike with long range, premium components, and precision handling.',
    features: ['Track Suspension', 'Quick Shift Display', 'Mobile Navigation', 'Regenerative Braking', 'Sport Mode', 'Smart Battery Management'],
    inStock: true,
  },
  {
    id: 'regal-pro',
    name: 'REGAL PRO',
    slug: 'regal-pro',
    price: 139999,
    originalPrice: 159999,
    images: [
      `https://images.unsplash.com/photo-1558980664-10e7170b5df9${Q}`,
      `https://images.unsplash.com/photo-1607091083645-31f4e28dc9af${Q}`,
    ],
    category: 'Electric Bikes',
    badge: 'Pro Series',
    specs: {
      range: '200 km',
      topSpeed: '115 km/h',
      motor: '2800W PMSM',
      battery: '72V 50Ah Lithium',
      chargingTime: '4 Hours',
      weight: '90 kg',
    },
    colors: ['#1b2631', '#d35400', '#7f8c8d'],
    description: 'High-performance electric bike with sport-tuned suspension and long-distance capability.',
    features: ['Dual Suspension', 'Removable Battery', 'App Connectivity', 'Disc Brakes', 'Rider Modes'],
    inStock: true,
  },
  {
    id: 'urban-rider',
    name: 'URBAN RIDER',
    slug: 'urban-rider',
    price: 119999,
    originalPrice: 129999,
    images: [
      `https://images.unsplash.com/photo-1607091083645-31f4e28dc9af${Q}`,
      `https://images.unsplash.com/photo-1558981403-c5f9899a28bc${Q}`,
    ],
    category: 'Electric Bikes',
    badge: 'Urban',
    specs: {
      range: '160 km',
      topSpeed: '100 km/h',
      motor: '2200W PMSM',
      battery: '72V 40Ah Lithium',
      chargingTime: '4.5 Hours',
      weight: '88 kg',
    },
    colors: ['#34495e', '#27ae60', '#e67e22'],
    description: 'A nimble electric bike built for city rides with comfortable ergonomics and reliable range.',
    features: ['Bluetooth App', 'LED Matrix Headlamp', 'Disc Brakes', 'Eco/Sport Mode'],
    inStock: true,
  },
  {
    id: 'street-x',
    name: 'STREET X',
    slug: 'street-x',
    price: 129499,
    originalPrice: 144999,
    images: [
      `https://images.unsplash.com/photo-1607088797610-020db7a14cd5${Q}`,
      `https://images.unsplash.com/photo-1623079399942-368de709ea32${Q}`,
    ],
    category: 'Electric Bikes',
    badge: 'Street',
    specs: {
      range: '180 km',
      topSpeed: '110 km/h',
      motor: '2600W PMSM',
      battery: '72V 45Ah Lithium',
      chargingTime: '4 Hours',
      weight: '91 kg',
    },
    colors: ['#2c3e50', '#8e44ad', '#ecf0f1'],
    description: 'Balanced performance and comfort for daily commuters and weekend riders.',
    features: ['Quick Shift Display', 'Traction Control', 'Removable Battery', 'Regenerative Braking'],
    inStock: true,
  },
];

export const getProductBySlug = (slug: string) => products.find(p => p.slug === slug);
export const getProductsByCategory = (category: string) => products.filter(p => p.category === category);
export const categories = ['All', ...Array.from(new Set(products.map(p => p.category)))];
